version: "3.7"
services:
  cli:
    image: node
    env_file:
      - .env
    volumes:
      - ./cli:/home/node/app
    user: node
    command: yarn sev
    working_dir: /home/node/app
    networks:
      - backend
      - xdai
  solidity:
    image: node
    env_file:
      - .env
    volumes:
      - ./solidity:/home/node/app
    user: node
    command: yarn truffle
    working_dir: /home/node/app
    links:
      - ganache
    networks:
      - backend
      - xdai
  ganache:
    image: node
    env_file:
      - .env
    volumes:
      - ./solidity:/home/node/app
    user: node
    command: yarn ganache-cli --fork http://nethermind-xdai:8545 --port 7545 --mnemonic "egg multiply pizza way almost type alarm romance again strategy peanut mule"
    working_dir: /home/node/app
    ports:
      - 7545:7545
    expose:
      - 7545
    networks:
      - backend
      - xdai
networks:
  backend:

  xdai:
    external:
      name: nethermind-xdai