version: "3.7"
services:
  cli:
    image: node
    env_file:
      - .env
    volumes:
      - ./cli:/home/node/app
    user: node
    command: yarn sev
    working_dir: /home/node/app
  solidity:
    image: node
    env_file:
      - .env
    volumes:
      - ./solidity:/home/node/app
    user: node
    command: yarn truffle
    working_dir: /home/node/app
  ganache:
    image: node
    env_file:
      - .env
    volumes:
      - ./solidity:/home/node/app
    user: node
    command: yarn ganache-cli
    working_dir: /home/node/app
networks:
  backend:

  xdai:
    external:
      name: nethermind-xdai